### ISSUE TITLE
Possible bug in mitm-rewrite logic ?

### ISSUE THREAD

**Issue by paoloantinori** [KevCui/mitm-scripts#1]
Hi there, 
thanks for this useful repo.

I was playing with your first example, `mitm-rewrite`.

I've found it useful but also either bugged or hiding a side effect that was not obvious from the Readme:

Since the behavior is implemented in `response` method instead of `request`, the original request is still forwarded to the original URL.

Using `request`, would fully short circuit the communication and work without hitting the real endpoint.

You can verify this is what's happening if you run `mitmdump` adding the `-v` flag.

I've noticed this because in my case, I was mocking a host that blacklisted me, so dropping all my calls. With the rule still implemented of `response` the behavior never worked, since I've never got any response from the server.

This is my version, in case the behavior depends on it:

```
17:03 $ /data/sw/mitm/mitmdump --version
Mitmproxy: 5.1.1 binary
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-5.6.7-300.fc32.x86_64-x86_64-with-fedora-32-Thirty_Two
```

**Comment by KevCui** [comment]
Hi @paoloantinori,

Thanks for your question! The idea of `mitm-rewrite` is mainly to change the response (json) body "in the middle" while the response is sending to client side from sever side. So, you are very right that the original request is still sent to server when using `mitm-rewrite`.

In your case, as my understanding, it's better to kill the flow `flow.kill()` to drop the request since you won't need/receive any responses. For example: https://stackoverflow.com/questions/50657347/how-to-block-url-using-mitmproxy/51077823#51077823

**Comment by KevCui** [comment]
Add a script `mitm-kill-request`. This script will kill/drop requests accordingly. b12c75dd0feeca11f471413801107579b25922ee

**Comment by paoloantinori** [comment]
Sorry, forgot to comment back!

Thank you!
